import { config } from './config';
export const publicPages = {
    services: { title: 'Private watch sourcing', description: 'A private request desk for watch sourcing and trade-in inquiries.', sections: [
            { heading: 'A brief shaped around you', body: 'Start with a brand and model, an exact reference, or a description of what you would like. Share your preferred condition, timing, and budget in USD. If your configuration is still open, choose guidance and tell us what matters most.' },
            { heading: 'From request to discussion', body: 'After you send your request, you receive an email receipt. The private desk reviews your brief and follows up through your selected contact method. Availability, condition, price, and any delivery arrangements must be confirmed before a purchase.' },
            { heading: 'One request, several watches', body: 'You can request several watches in one inquiry, each with its own preferences. Trade-in watches are described separately, including condition, presentation, and an optional expected value. Estimates are not final appraisals.' },
            { heading: 'Information for a trade appraisal', body: 'Include the brand, model, reference if known, condition, and what comes with each watch. Your concierge may ask for photos of the dial, caseback, box, papers, and other included items. Do not upload sensitive documents through the request form.' },
        ] },
    faq: { title: 'Questions before your request', description: 'How private watch requests, budgets, trade-ins, and contact preferences work.', sections: [
            { heading: 'Do I need an exact reference?', body: 'No. A model, collection, or description is enough to begin a guided search. An exact reference and configuration can help the private desk understand your preferences.' },
            { heading: 'Is this a live inventory list?', body: 'No. The catalog offers examples to help describe a sourcing inquiry. A listed model or reference does not confirm stock, price, or availability.' },
            { heading: 'Can I request more than one watch?', body: 'Yes. Add another requested watch after choosing its budget. Each watch has its own condition, occasion, timing, and budget preferences.' },
            { heading: 'Can I offer multiple watches in trade?', body: 'Yes. Add each trade-in separately and describe its condition and presentation. Any expected value is a starting point for discussion, not an accepted valuation.' },
            { heading: 'Which currency do you use?', body: 'All budgets and expected trade-in values in this form use USD.' },
            { heading: 'Why is an email address required?', body: 'We send an email confirmation with your request ID. You can still choose Text, WhatsApp, Email, or Call for the concierge’s personal follow-up.' },
            { heading: 'Does sending a request place an order?', body: 'No. A request begins a conversation. It is not a purchase, a reservation, or a promise that a watch is available.' },
            { heading: 'Where is my draft saved?', body: 'Your unfinished request is saved in session storage in this browser tab when available. A completed request is cleared from that draft storage after it has been safely received.' },
        ] },
    privacy: { title: 'Privacy', description: 'How Omni handles private request information, drafts, receipts, and measurement.', sections: [
            { heading: 'Information you provide', body: 'We collect watch preferences, budgets, trade-in details, location, email, and any phone number you provide to review and respond to your request. Do not include payment details, identity documents, or passwords.' },
            { heading: 'How information is used', body: 'Omni uses your information to respond through your selected contact method and send a transactional email receipt. Information may be shared with service providers and sourcing partners when needed to handle the request. We do not sell the information you submit.' },
            { heading: 'Drafts and retention', body: `Unfinished drafts, including contact details, use browser session storage. Submitted inquiry details are retained in the app database for ${config.retentionDays} days and then purged. Email records and any separately maintained customer records have separate retention; removing an app record does not delete email copies. Theme preference is stored separately on your device.` },
            { heading: 'Service providers and security', body: 'The application uses hosting, database, queue, and email services to process requests. We restrict access to submitted data, avoid putting contact details in application logs, and use temporary hashed identifiers to limit abusive submissions.' },
            { heading: 'Advertising measurement', body: 'On the production site, Google Ads measurement records a conversion when an inquiry is safely saved. Contact details and free-text watch briefs are not sent through this measurement feature, and enhanced conversions are disabled. Measurement does not load when your browser sends Global Privacy Control or Do Not Track.' },
            { heading: 'Contact and deletion requests', body: 'You can reply to your request confirmation or use the contact options on the Omni Timepieces website to ask about your information, request corrections, or request deletion. We may retain information when required to fulfill obligations connected with your inquiry.' },
        ] },
    terms: { title: 'Terms of the private request service', description: 'Important information about sourcing inquiries, availability, and trade appraisals.', sections: [
            { heading: 'An inquiry, not an order', body: 'Submitting this form starts a discussion with Omni Timepieces. It does not create a purchase, reserve a watch, accept a trade, or guarantee availability.' },
            { heading: 'Catalog examples', body: 'Models, references, dial options, and configurations are examples to help describe your request. They are not a statement of current stock. Brand names identify the watches you are interested in; they do not imply an official manufacturer relationship.' },
            { heading: 'Pricing and delivery', body: 'Budgets are expressed in USD. Prices, taxes, condition, payment terms, and delivery arrangements must be confirmed separately before a transaction. Timing preferences are requests, not delivery guarantees.' },
            { heading: 'Trade-in requests', body: 'Expected trade values are provided by you for discussion. A final appraisal requires review of the watch, its condition, and its included items. Submitting trade details is not an agreement to buy the watch.' },
            { heading: 'Contact permission', body: 'By confirming contact consent, you authorize follow-up about this inquiry through your chosen method and an email receipt. This consent does not subscribe you to unrelated marketing.' },
        ] },
};
export const brandPages = [
    { slug: 'rolex', name: 'Rolex', intro: 'For a Rolex request, the model and exact reference help distinguish case metal, dial, bezel, and bracelet preferences.', focus: 'GMT-Master II and Datejust requests can benefit from an Oyster or Jubilee preference. For Daytona, describe the dial and whether you are considering a metal bracelet or Oysterflex. If you are unsure, leave configuration open.', trade: 'Include any reference, service history you know, and the box or card supplied with the watch.' },
    { slug: 'patek-philippe', name: 'Patek Philippe', intro: 'Begin with the collection, such as Nautilus, Aquanaut, Calatrava, or a complication, and add the full reference when known.', focus: 'Case metal, dial execution, and bracelet or strap can distinguish closely related requests. For an Aquanaut, describe your strap preference; for a complication, identify the function that matters to you.', trade: 'Describe the included presentation and any service records. The private desk can discuss which additional details are needed for evaluation.' },
    { slug: 'audemars-piguet', name: 'Audemars Piguet', intro: 'A Royal Oak, Royal Oak Offshore, Code 11.59, or Royal Oak Concept request begins with its collection and reference.', focus: 'Share the case material, dial execution, size preference in your notes, and bracelet or strap. An openworked or specific Tapisserie preference is useful to state explicitly.', trade: 'Include the reference, condition, presentation, and any supplied interchangeable straps.' },
    { slug: 'richard-mille', name: 'Richard Mille', intro: 'For Richard Mille, the RM number is the primary starting point. Include a named edition when known.', focus: 'Case construction and strap color can be central to the brief. Describe titanium, ceramic, Carbon TPT, Quartz TPT, sapphire, or another desired construction without assuming availability.', trade: 'Describe the exact RM reference, edition, condition, and included presentation. If a detail is uncertain, say so rather than guessing.' },
    { slug: 'vacheron-constantin', name: 'Vacheron Constantin', intro: 'Start with the collection, such as Overseas, Patrimony, Traditionnelle, Historiques, or Fiftysix.', focus: 'For an Overseas inquiry, describe the reference, dial, case metal, and whether a bracelet or an interchangeable strap set matters to you. For a dress watch, include the functions and proportions you prefer in your brief.', trade: 'List included bracelets, straps, papers, and packaging individually when you know them.' },
    { slug: 'fp-journe', name: 'F.P. Journe', intro: 'The model name and reference code, when known, establish the starting point for an F.P. Journe request.', focus: 'Describe the case material, dial or edition, and bracelet or strap. Chronomètre Bleu, Élégante, Chronomètre Souverain, Résonance, and Octa inquiries can each benefit from a precise configuration brief.', trade: 'Provide the model, case material, included presentation, and any known service information without filling in uncertain details.' },
    { slug: 'omega', name: 'OMEGA', catalogName: 'Omega', intro: 'Begin with the collection and reference for an OMEGA inquiry, such as Speedmaster, Seamaster, Constellation, or De Ville.', focus: 'The full reference helps describe the intended version. Add dial, case material, and bracelet or strap preferences, along with any specific movement or edition requirements in your notes.', trade: 'Describe the condition, included box and papers, reference, and any bracelet or strap supplied with the watch.' },
];
