'use client';
import Link from 'next/link';
import { config } from '@/lib/config';
import { useRequest } from './providers';
export function RequestReview() {
    const { state, dispatch } = useRequest();
    return <div className="request-review">{state.watches.map((w, i) => <section className="review-card" key={w.id}><div className="review-heading"><h3>Watch {i + 1} · {w.brand} {w.model}</h3><button type="button" className="quiet-button" onClick={() => { dispatch({ type: 'watch/switch', id: w.id }); dispatch({ type: 'navigate', step: 1 }); }}>Edit watch {i + 1}</button></div><dl className="review-details">{Object.entries({ Reference: w.reference || 'Open', Configuration: [w.year, w.dial, w.caseMaterialOther || w.caseMaterial, w.braceletOther || w.bracelet].filter(Boolean).join(' · ') || 'Open', Occasion: w.occasion, Condition: w.condition, Timing: w.timeline, Budget: w.budget === 'Custom' ? `${w.budgetMin || 0}–${w.budgetMax || '?'} ${config.currency}` : `${w.budget} · ${config.currency}` }).map(([key, value]) => <div key={key}><dt>{key}</dt><dd>{value}</dd></div>)}</dl></section>)}
 {state.tradeIn === 'Yes' ? <section className="review-card"><h3>Trade-in watches</h3>{state.trades.map((t, i) => <div key={t.id}><h3>{i + 1}. {t.brand} {t.model}</h3><dl className="review-details">{Object.entries({Reference:t.reference || 'Open',Configuration:[t.year,t.dial,t.bracelet].filter(Boolean).join(' · ') || 'Open',Condition:t.condition,Presentation:t.setOther || t.set,'Expected value':t.expectedValue ? `${t.expectedValue} ${config.currency}` : 'Open'}).map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl></div>)}<button className="quiet-button" type="button" onClick={() => dispatch({ type: 'navigate', step: 6 })}>Edit trades</button></section> : null}
 <section className="review-card"><h3>Your introduction</h3><p>{state.contact.fullName} · {state.contact.location}</p><p>{state.contact.email}{state.contact.phone ? ` · ${state.contact.phone}` : ''}</p><p>Follow-up: {state.contact.preferredContact}</p><button className="quiet-button" type="button" onClick={() => dispatch({ type: 'navigate', step: 7 })}>Edit contact details</button></section>
 <label className="consent"><input type="checkbox" checked={state.consent} onChange={e => dispatch({ type: 'update', patch: { consent: e.target.checked } })}/><span>I agree that Omni Timepieces may contact me about this request through my selected method and send a confirmation email.</span></label><p className="helper">Read our <Link href="/privacy">Privacy policy</Link> and <Link href="/terms">Terms</Link>.</p></div>;
}
